version: "3.7"
services:
  nrpc:
    build:
      context: ./containers/nrpc
    ports:
      - "9080:80"
    networks:
      - poc
    depends_on:
      - xyz-bff
      - abc-bff
  xyz-bff:
    build:
      context: ./containers/xyz-bff
    ports:
      - "13000:3000"
    networks:
      - poc
  abc-bff:
    build:
      context: ./containers/abc-bff
    ports:
      - "23000:3000"
    networks:
      - poc

networks:
  poc:
